#!/bin/bash
#### Check if the acmHostname is found, read it and compare to the current hostname
### If, they are the same, dont do anything
### If, the file is not found,this means 1st time run the PC,
###	add to it current hostname, create the home directory and set profile settings, and if there is a backup, restore it
### else, if it is found anad has a value different than the current,
###	delete the home directory for the old user,
###	And repeat the steps as the file is not found

################################ Script is written by:
############# Eng. Ahmed M. ElSayed
###############   ahmed.elsayed@acmacpc.org


function createUserProfile {
curHostName=`hostname`
useradd -c "Print Server user" -m print
mkdir /home/print/Deskto
######################## We have here to create the desktop shortcuts
echo $curHostName > /etc/acmHostname
### Downloading all shortcuts
cd /home/print/Desktop
wget http://control/prog/common/cups.desktop
chmod +rx *.desktop
chown -R print /home/print
}

curHostName=`hostname`
if [ ! -f /etc/acmHostname ]
then
	createUserProfile
	exit 0
fi
oldHostName=`cat /etc/acmHostname`
if [ $oldHostName != $curHostName ]
then
 rm -Rf /home/$oldHostName
 createUserProfile
fi
