#!/bin/sh

### BEGIN INIT INFO
# Provides:          finalize
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/stop apache2 web server
### END INIT INFO

######################################### Finalize script
# Is used to perform any additional tasks Just after the machine rebooted after
#   installation
########################################

cd /tmp

### 10- Download the server public key

wget http://control/prog/common/authorized_keys
mkdir /root/.ssh
sudo cp authorized_keys /root/.ssh
sudo rm authorized_keys

### 20- update the mirror list

 wget http://control/prog/common/sources.list
 cp sources.list /etc/apt
 rm sources.list


### 30- update the mirror list

 apt-get update

### 40- Install editors (Geany, netbeans, eclipse, codeblocks)


 apt-get -y --force-yes install nfs-kernel-server apache2   
 update-rc.d nfs-kernel-server defaults
#apt-get -y --force-yes install nis


### 50- Disbale guest login, and change the login to manual
 echo "allow-guest=false" >> /usr/share/lightdm/lightdm.conf.d/50-ubuntu.conf
 echo "greeter-show-manual-login=true" >> /usr/share/lightdm/lightdm.conf.d/50-ubuntu.conf

### 60- Download iptablesload script, and iptables rules files
 wget http://control/roles/webserver/iptables.rules
 wget http://control/prog/common/iptablesload
 mv iptables.rules /etc/
 mv iptablesload /etc/network/if-pre-up.d
 chmod +x /etc/network/if-pre-up.d/iptablesload

### 70- Downloading cups configuration files
 wget http://control/prog/common/cupsd.conf
 mv cupsd.conf /etc/cups

### 80- Configure nis client

 if [ -f /etc/yp.conf ] 
 then
  rm /etc/yp.conf
 fi
 echo "ACMACPC" > /etc/defaultdomain
 apt-get -y --force-yes install portmap
 echo "ACMACPC" > /tmp/nis.seed
 debconf-set-selections /tmp/nis.seed
 apt-get -y --force-yes install nis
 echo "domain ACMACPC server control" > /etc/yp.conf
 wget http://control/prog/common/nis
 cp nis /etc/default/nis 
 rm nis
 wget http://control/prog/common/nsswitch.conf
 cp nsswitch.conf /etc
 rm nsswitch.conf
 update-rc.d portmap defaults
 update-rc.d ypbind defaults
 domainname ACMACPC
 ypdomainname ACMACPC
 service portmap restart
 service ypbind restart

 echo "+::::::" >> /etc/passwd
 echo "+::::::::" >> /etc/shadow
 echo "+:::" >> /etc/group
 ### Chancing the administrator uid to 750 .. anyid less than 1000
 usermod -u 750 administrator
 chown -R administrator /home/administrator

### 90- Creating backupdirectory & scoreboard & stldocs & samples
 mkdir /backup /var/www/scoreboard /var/www/stldocs /home/samples /home/JudgeCases

### 100- Adding /backup to exportfs
 echo "/backup *(rw,no_root_squash,no_subtree_check)" >> /etc/exports
 echo "/var/www/scoreboard pc2(rw,no_root_squash,no_subtree_check)" >> /etc/exports
 N=`wc -l /adm/etc/judgesmac|awk ' { print $1 } '`
 for i in `seq 1 $N`
 do
   echo "/home/samples judge$i(rw,no_root_squash,no_subtree_check)">> /etc/exports
   echo "/home/JudgeCases judge$i(rw,no_root_squash,no_subtree_check)">> /etc/exports
 done
 echo "/home/samples *(ro,no_root_squash,no_subtree_check)">> /etc/exports 
  service nfs-kernel-server restart


### 110-Enable Scoreboard virtual directory
 wget http://control/roles/webserver/htaccess.scoreboard
 cp htaccess.scoreboard /etc/apache2/sites-enabled
 rm htaccess.scoreboard

### 120- Ebale STLDocs virtual directory
 wget http://control/roles/webserver/htaccess.stldocs
 cp htaccess.stldocs /etc/apache2/sites-enabled
 rm htaccess.stldocs

### 130- Prepare STLDocs
 wget http://control/roles/webserver/stldocs.tar
 cd /var/www/stldocs
 tar xf /tmp/stldocs.tar
 cd /tmp
 rm stldocs.tar

### 140- Add the virtual directory to apache2 
 sed -e '2 a Include /etc/apache2/sites-enabled/htaccess.stldocs' -e '2 a Include /etc/apache2/sites-enabled/htaccess.scoreboard' /etc/apache2/sites-enabled/000-default.conf > /tmp/000-default.conf
 cp /tmp/000-default.conf /etc/apache2/sites-enabled/000-default.conf
 rm /tmp/000-default.conf
 service apache2 restart

### 150- Create the samples, JudgeCases to be shared
 chgrp -R judges /home/samples /home/JudgeCases
 chmod 775 /home/samples /home/JudgeCases

### 160- creates css and images directories, and then download css and png files to created directories
mkdir /var/www/scoreboard/css /var/www/scoreboard/images
wget http://control/roles/webserver/scoreboard/css/bootstrap.css
wget http://control/roles/webserver/scoreboard/css/bootstrap-responsive.min.css
wget http://control/roles/webserver/scoreboard/css/style.css
wget http://control/roles/webserver/scoreboard/images/flag.png
wget http://control/roles/webserver/scoreboard/images/logo.png
mv *.css /var/www/scoreboard/css
mv *.png /var/www/scoreboard/images



exit 0
