#!/bin/bash
#### Check if the acmHostname is found, read it and compare to the current hostname
### If, they are the same, dont do anything
### If, the file is not found,this means 1st time run the PC,
###	add to it current hostname, create the home directory and set profile settings, and if there is a backup, restore it
### else, if it is found anad has a value different than the current,
###	delete the home directory for the old user,
###	And repeat the steps as the file is not found

################################ Script is written by:
############# Eng. Ahmed M. ElSayed
###############   ahmed.elsayed@acmacpc.org


function createUserProfile {
curHostName=`hostname`
mkdir -p /home/$curHostName/Desktop/work
mkdir /home/$curHostName/Desktop/samples
mkdir /home/$curHostName/Desktop/JudgeCases
######################## We have here to create the desktop shortcuts
mkdir -p /home/$curHostName/.config/autostart
cp /home/administrator/.config/autostart/set*.desktop /home/$curHostName/.config/autostart
chmod +x /home/$curHostName/.config/autostart/set*.desktop
chown -R $curHostName:judges /home/$curHostName
chown -R $curHostName:judges /home/$curHostName/.config
echo $curHostName > /etc/acmHostname
### Downloading all shortcuts
cd /home/$curHostName/Desktop
wget http://control/prog/common/CodeBlocks.desktop
wget http://control/prog/common/ECLipse.desktop
wget http://control/prog/common/Geany.desktop
wget http://control/prog/common/GEdit.desktop
wget http://control/prog/common/Net_Beans.desktop
wget http://control/prog/common/PC2_Team.desktop
wget http://control/prog/common/ScoreBoard.desktop
wget http://control/prog/common/STL_Documentation.desktop
wget http://control/prog/common/PC2_Judge.desktop
wget http://control/prog/common/BCompare.desktop
sudo chown administrator *.desktop
chmod +rx *.desktop
}

function mountSamples {
judgeName=$1
#mount the directory as rw for judges
mount -o rw web:/home/samples /home/$judgeName/Desktop/samples
mount -o rw web:/home/JudgeCases /home/$judgeName/Desktop/JudgeCases
}

function unmountSamples {
judgeName=$1
umount /home/$judgeName/Desktop/samples

umount /home/$judgeName/Desktop/JudgeCases
}

curHostName=`hostname`
if [ ! -f /etc/acmHostname ]
then
	createUserProfile
	mountSamples $curHostName
	exit 0
fi
oldHostName=`cat /etc/acmHostname`
if [ $oldHostName != $curHostName ]
then
unmountSamples $oldHostName
rm -Rf /home/$oldHostName
createUserProfile
fi
mountSamples $curHostName

